Models/LoaiSanPham.cs
using Cl.DataAccess.EF.Query;
using System.ComponentModel.DataAnnotations;

namespace TestDev.Models
{
    public class LoaiSanPham : CoreEntity
    {
        public string? Ten {  get; set; }
        public DateTime NgayNhap { get; set; }
        public List<SanPham_LoaiSanPham> SanPham_LoaiSanPhams { get; set; } = new();
    }
    public class CoreEntity
    {
        [Key]
        public int Id { get; set; }
    }
    public class LoaiSanPhamQuery : BaseQuery
    {

    }
    public class LoaiSanPhamEntity : LoaiSanPham
    {
        public int SoLuongSanPham { get; set; }   
    }
}

Controllers/LoaiSanPhamController.cs
using Cl.DataAccess.EF;
using Cl.DataAccess.EF.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using TestDev.Models;

namespace TestDev.Controllers
{
    public class LoaiSanPhamController : Controller
    {
        private readonly LoaiSanPhamRepository _LoaiSanPhamRepository;
        private readonly ResponeActionResult _responeActionResult;
        public LoaiSanPhamController(LoaiSanPhamRepository LoaiSanPhamRepository, ResponeActionResult responeActionResult)
        {
            _LoaiSanPhamRepository = LoaiSanPhamRepository;
            _responeActionResult = responeActionResult;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetPaged(LoaiSanPhamQuery query)
        {
            try
            {
                var lstTask = _LoaiSanPhamRepository.GetPaged(query);
                if (lstTask == null)
                {
                    return BadRequest(_responeActionResult.Message($"Không tìm thấy bản ghi"));
                }
                _responeActionResult.data = lstTask;
                _responeActionResult.draw = query.draw;
                _responeActionResult.recordsTotal = _LoaiSanPhamRepository.TotalRecord;
                _responeActionResult.recordsFiltered = _LoaiSanPhamRepository.TotalRecord;
                return Ok(_responeActionResult);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }
        public IActionResult View(int Id)
        {
            LoaiSanPham LoaiSanPham = new LoaiSanPham();
            if (Id != 0)
            {
                var a = _LoaiSanPhamRepository.GetById(Id);
                if (a != null) LoaiSanPham = a;
            }
            return PartialView(LoaiSanPham);
        }
        public IActionResult Edit(int Id)
        {
            LoaiSanPham oTask = new LoaiSanPham();
            if (Id != 0)
            {
                oTask = _LoaiSanPhamRepository.GetById(Id);
                if (oTask == null) { oTask = new LoaiSanPham(); }
            }
            return View(oTask);
        }
        [HttpPost]
        public IActionResult Update(LoaiSanPham LoaiSanPhamInput)
        {
            try
            {
                if (LoaiSanPhamInput == null || LoaiSanPhamInput.Id == 0)
                {
                    return BadRequest(_responeActionResult.Message($"Bản ghi không hợp lệ"));
                }
                LoaiSanPham oLoaiSanPham = _LoaiSanPhamRepository.GetById(LoaiSanPhamInput.Id);
                oLoaiSanPham.Ten = LoaiSanPhamInput.Ten;
                oLoaiSanPham.NgayNhap = LoaiSanPhamInput.NgayNhap;


                _LoaiSanPhamRepository.Save();
                _responeActionResult.ex_message = "Sửa thành công";
                _responeActionResult.data = new LoaiSanPham() { Id = LoaiSanPhamInput.Id };
                return Ok(_responeActionResult);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }
        [HttpPost]
        public IActionResult Insert(LoaiSanPham LoaiSanPhamInput)
        {

            try
            {
                _LoaiSanPhamRepository.Add(LoaiSanPhamInput);
                _LoaiSanPhamRepository.Save();
                _responeActionResult.ex_message = "Thêm thành công";
                _responeActionResult.data = new LoaiSanPham() { Id = LoaiSanPhamInput.Id };
                return Ok(_responeActionResult);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }
        [HttpGet]
        public IActionResult Delete(int Id)
        {
            try
            {
                _LoaiSanPhamRepository.DeleteById(Id);
                _LoaiSanPhamRepository.Save();
                _responeActionResult.ex_message = "Xóa thành công";
                _responeActionResult.data = null;
                return Ok(_responeActionResult);
            }
            catch (Exception ex)
            {
                Exception inner = ex.InnerException;
                if (inner is SqlException sqlEx)
                {
                    if (sqlEx.Number == 547)
                    {
                        if (sqlEx.Message.Contains("dbo.GiaoViecs"))
                        {
                            return BadRequest(_responeActionResult.Message($" Đã có Giao Việc sử dụng trong Task này"));
                        }

                    }
                }
                return BadRequest();
                //Log.Error(ex, "Lỗi khi xóa");
                //return StatusCode(500, "Đã có lỗi xảy ra khi xóa người dùng. Vui lòng thử lại sau.");
            }

        }
    }
}

Views/LoaiSanPham/Edit.cshtml
@model TestDev.Models.LoaiSanPham

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>
                    @if (Model.Id > 0)
                    {
                        <text>Sửa chuyến</text>
                    }
                    else
                    {
                        <text>Thêm mới chuyến</text>
                    }
                </h4>
            </div>
            <div class="col-6 d-none d-md-block">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/chuyen/index">
                            <svg class="stroke-icon">
                                <use href="/202404/images/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item">Chuyến</li>
                    <li class="breadcrumb-item active">
                        @if (Model.Id > 0)
                        {
                            <text>Sửa chuyến</text>
                        }
                        else
                        {
                            <text>Thêm mới chuyến</text>
                        }
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="@(Model.Id == 0 ? "Insert" : "Update")" asp-controller="LoaiSanPham" method="post" class="card needs-validation">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <!-- Tiêu đề bên trái -->
                    <h4 class="mb-0">Thông tin bản ghi</h4>

                </div>

                <div class="card-body custom-input">
                    <div class="row" id="dropdownParent">
                        @if (Model.Id > 0)
                        {
                            <input asp-for="Id" type="hidden" />
                        }
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="Ten" class="form-label">Tên</label>
                                <input asp-for="Ten" class="form-control " placeholder="Tên" required/>
                                <span asp-validation-for="Ten" class="text-danger"></span>
                            </div>
                        </div>
                        
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="NgayNhap" class="form-label">Ngày nhập</label>
                                @if (Model.Id > 0)
                                {
                                    <input id="NgayChay" name="NgayChay" type="text" class="form-control" value="@Model.NgayNhap.ToString("dd/MM/yyyy")" placeholder="Người chạy" required />
                                }
                                else
                                {
                                    <input id="NgayChay" name="NgayChay" type="text" class="form-control" value="@DateTime.Now.AddDays(1).ToString("dd/MM/yyyy")" placeholder="Người chạy" required />
                                }
                                <span asp-validation-for="NgayNhap" class="text-danger"></span>
                            </div>
                        </div>
                        

                        <div class="col-md-12 text-end">
                            <button id="save" type="button">Lưu</button>
                        </div>
                    </div>


                </div>


            </form>
        </div>
    </div>

</div>
<script>
    function convertToDateTimeLocal(datetimeStr) {
        var dateParts = datetimeStr.split('/');
        var year = dateParts[2];
        var month = dateParts[1];
        var day = dateParts[0];
        //return `${year}-${month}-${day}T${00}:${00}`;
        return `${month}/${day}/${year}`;
    }

    $(document).ready(function () {
        $('.nc').hide();
        $('#checkbox').on('change', function () {
            if (this.checked) {
                $('.nc').show();
            } else {
                $('.nc').hide();
            }
        });
        $('#NgayChay').datepicker({
            language: 'vi',
            defaultDate: new Date(),
            autoClose: true
        });
        $('#save').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    var form = $("form.needs-validation")[0];
                    if (!form.checkValidity()) {
                        resolve();//Đặt cờ thành công
                        event.preventDefault();
                        event.stopPropagation();
                    } else {
                        event.preventDefault();
                        event.stopPropagation();
                        let NgayChay = $("#NgayChay").val().trim();
                        if (NgayChay && !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(NgayChay)) {
                            $("#NgayChay").val(convertToDateTimeLocal(NgayChay));
                        }

                        var data = new FormData(form);
                        var xhr = new XMLHttpRequest();
                        xhr.open(form.method, form.action, true);
                        xhr.onload = function () {
                            resolve();//Đặt cờ thành công
                            if (xhr.status === 200) {
                                $("#NgayChay").val(NgayChay);
                                
                                ChuyenHuong("backWithReloadGrid", null, null, "data-source-4");
                            } else {
                                $("#NgayChay").val(NgayChay);
                                showNotification("warning", "Thao tác thất bại: " + JSON.parse(xhr?.response).ex_message)
                            }
                        };
                        xhr.send(data);

                    };
                    form.classList.add('was-validated');


                });
            }
        });






        var initialSelection = [];
        $("#NguoiDungId").registerSelect({
            url: '/NguoiDung/GetPaged',
            placeholder: "Chọn người chạy",
            queryData: {
            },
            dropdownParent: "#dropdownParent",
            initialSelection: initialSelection,
            prepareDataRequest: function (params) {
                return {
                    Keyword: params.term,
                    SearchIn: ["TenNguoiDung"],
                };
            },
            dataProcess: function (data) {
                const results = data.data
                    .sort((a, b) => a.TenNguoiDung.localeCompare(b.TenNguoiDung))
                    .map(item => ({
                        id: item.Id,
                        text: item.TenNguoiDung
                    }));

                return { results };
            },
        });
        $("#DiaDiemLayDatId").registerSelect({
            url: '/DiaDiemLayDat/GetPaged',
            placeholder: "Chọn địa điểm lấy đất",
            queryData: {
            },
            dropdownParent: "#dropdownParent",
            initialSelection: initialSelection,
            prepareDataRequest: function (params) {
                return {
                    Keyword: params.term,
                    SearchIn: ["TenDiaDiem"],
                };
            },
            dataProcess: function (data) {
                const results = data.data
                    .sort((a, b) => a.TenDiaDiem.localeCompare(b.TenDiaDiem))
                    .map(item => ({
                        id: item.Id,
                        text: item.TenDiaDiem
                    }));

                return { results };
            },
        });
        $("#DiaDiemDoId").registerSelect({
            url: '/DiaDiemDo/GetPaged',
            placeholder: "Chọn địa điểm đổ",
            queryData: {
            },
            dropdownParent: "#dropdownParent",
            initialSelection: initialSelection,
            prepareDataRequest: function (params) {
                return {
                    Keyword: params.term,
                    SearchIn: ["TenDiaDiem"],
                };
            },
            dataProcess: function (data) {
                const results = data.data
                    .sort((a, b) => a.TenDiaDiem.localeCompare(b.TenDiaDiem))
                    .map(item => ({
                        id: item.Id,
                        text: item.TenDiaDiem
                    }));

                return { results };
            },
        });

    });

</script>

Views/LoaiSanPham/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<style>
    #data-source-4_processing {
        display: none !important;
    }

    #data-source-4 i {
        font-size: 25px;
        padding-right: 5px;
        color: var(--theme-deafult);
    }

</style>

<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>Danh sách chuyến chạy</h4>
            </div>
            <div class="col-6 d-none d-md-block">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/chuyen/index">
                            <svg class="stroke-icon">
                                <use href="/202404/images/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item">Chuyến</li>
                    <li class="breadcrumb-item active">Danh sách chuyến</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row size-column">
        <div class="col-12 box-col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row" id="dropdownParent">
                        <div class="col-md-3 mb-2">
                            <label class="form-label" for="search-input">Nhập biển số xe...</label>
                            <input type="text" class="form-control" id="search-input" autocomplete="off">
                        </div>
                        <div class="col-md-4 text-center mt-md-4">
                            <button class="btn btn-primary" id="search-btn">Tìm kiếm</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row size-column">
        <div class="col-12 box-col-12">
            <div class="card">

                <div class="card-body mt-2">
                    <div class="table-responsive custom-scrollbar">
                        <table class="display" id="data-source-4" style="width:100%">
                        </table>
                    </div>
                </div>
                <div class="card-header pb-3 py-1 card-no-border">
                    <div class="row">
                        <div class="col-12 mt-0 text-end">
                            <button id="ThemMoi" type="button" data-permission="002002001"> Thêm mới</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script>
    function xemChuyen(Id) {
        openModalWithApi("/Chuyen/View/" + Id, "xl");
    };
    function suaChuyen(Id) {
        ChuyenHuong("external", "/LoaiSanPham/Edit/" + Id);
    };
    function xoaChuyen(Id) {


        toggleButtonContainerLoading(Id);
        showNotificationWithConfirm("",
            () => {
                $.ajax({
                    url: '/LoaiSanPham/Delete/' + Id,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        toggleButtonContainerLoading(Id);
                        showNotification("warning", "Xóa thành công")
                        $('#search-btn').click();
                    },
                    error: function (xhr, status, error) {
                        showNotification("danger", 'Đã có lỗi xảy ra:' + xhr?.responseJSON?.ex_message);
                        toggleButtonContainerLoading(Id);
                    }
                });
            },
            () => {
                toggleButtonContainerLoading(Id);
            })



    };

    $(document).ready(function () {
        var initialSelection = [];
        $("#NguoiChay").registerSelect({
            url: '/NguoiDung/GetPaged',
            placeholder: "Chọn người chạy",
            queryData: {
            },
            dropdownParent: "#dropdownParent",
            initialSelection: initialSelection,
            prepareDataRequest: function (params) {
                return {
                    Keyword: params.term,
                    SearchIn: ["TenNguoiDung"],
                };
            },
            dataProcess: function (data) {
                const results = data.data
                    .sort((a, b) => a.TenNguoiDung.localeCompare(b.TenNguoiDung))
                    .map(item => ({
                        id: item.Id,
                        text: item.TenNguoiDung
                    }));

                return { results };
            },
        });
        $("#DiaDiemLayDat").registerSelect({
            url: '/DiaDiemLayDat/GetPaged',
            placeholder: "Chọn địa điểm lấy đất",
            queryData: {
            },
            dropdownParent: "#dropdownParent",
            initialSelection: initialSelection,
            prepareDataRequest: function (params) {
                return {
                    Keyword: params.term,
                    SearchIn: ["TenDiaDiem"],
                };
            },
            dataProcess: function (data) {
                const results = data.data
                    .sort((a, b) => a.TenDiaDiem.localeCompare(b.TenDiaDiem))
                    .map(item => ({
                        id: item.Id,
                        text: item.TenDiaDiem
                    }));

                return { results };
            },
        });
        $("#DiaDiemDo").registerSelect({
            url: '/DiaDiemDo/GetPaged',
            placeholder: "Chọn địa điểm lấy đất",
            queryData: {
            },
            dropdownParent: "#dropdownParent",
            initialSelection: initialSelection,
            prepareDataRequest: function (params) {
                return {
                    Keyword: params.term,
                    SearchIn: ["TenDiaDiem"],
                };
            },
            dataProcess: function (data) {
                const results = data.data
                    .sort((a, b) => a.TenDiaDiem.localeCompare(b.TenDiaDiem))
                    .map(item => ({
                        id: item.Id,
                        text: item.TenDiaDiem
                    }));

                return { results };
            },
        });
        var dataGridInstance = $('#data-source-4').registerGrid({
            "columns": [
                {
                    "data": 'STT',
                    "title": "STT",
                    "render": function (data, type, row, meta) {
                        return Index = meta.row + meta.settings._iDisplayStart + 1;
                    },
                    "width": "30px",
                    "orderable": false,
                },
                {

                    "title": "Tên",
                    "render": function (data, type, row) {
                        return row.Ten ==null ? '' : `<span)'>${row.Ten}</span>`;                    },
                    "orderable": false,

                },
                {

                    "title": "Số lượng sản phẩm",
                    "render": function (data, type, row) {
                        return row.SoLuongSanPham;
                    },
                    "orderable": false,

                },
                                {
                    "data": 'NgayNhap',
                    "title": "Ngày Nhập",
                    "render": function (data, type, row) {
                        return data == null ? '' : `<span>${new Date(row.NgayNhap).toLocaleDateString('vi-VN', { day: '2-digit', month: '2-digit', year: 'numeric' })}</span>`;
                    },
                    "orderable": false,

                },
                {
                    "data": '',
                    "title": "Chức năng",
                    "render": function (data, type, row) {

                        var html = `<div class='button-container-in-grid button-container-${row.Id}'>`;
                        html += `<a href='#' title="Sửa " data-permission="002003002" onclick='suaChuyen(${row.Id})'><i class="fa fa-pencil" aria-hidden="true"></i></a>`
                        html += ` <a  title="Xóa" data-permission="002003003" onclick='xoaChuyen(${row.Id})'><i class="fa fa-trash-o" aria-hidden="true"></i></a>`
                        return html += "</div>";

                    },
                    "width": "100px",
                    "orderable": false,
                }

            ],
            length: 20,
            endpoint: "/LoaiSanPham/GetPaged",
            prepareRequest: function (d) {
                d.SearchIn = ["Ten"];
                var t_gridRequest = {
                    "skip": d.start,
                    "page": (d.start / d.length) + 1,
                    "pageSize": d.length
                };
                d.t_gridRequest = JSON.stringify(t_gridRequest);
                return d;
            },
            dataBound: function () {
                $("#data-source-4 thead tr th:first-child").removeClass();
                $("#data-source-4_info").hide();
            }

        });

        $('#search-btn').registerButton({
            type: 'primary',
            icon: "fa fa-search",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    var grid = dataGridInstance;
                    grid.page(0);//chuyển về trang đầu
                    grid.ajax.reload(null, false);
                    resolve();//cờ xác định kết thúc
                });
            }
        });
        $('#search-tu-ngay').datepicker({
            language: 'vi',
        });
        $('#search-den-ngay').datepicker({
            language: 'vi',
        });
        $('#exportExcel').registerButton({
            type: 'info',
            icon: "fa fa-file-excel-o",
            clickHandler: function () {
                var grid = dataGridInstance;
                return new Promise(function (resolve, reject) {
                    $.post("/Chuyen/ExportDataToExcel", {
                        "SearchIn": ["BienSo"],
                        "Keyword": $('#search-input').val(),
                        "TuNgay": $('#search-tu-ngay').val(),
                        "DenNgay": $('#search-den-ngay').val()
                    })
                        .done(function (data) {
                            ChuyenHuong("external", `/Files/ExportExcel?file=${data}`, "new_tab")
                            resolve(); // Kết thúc promise
                        })
                        .fail(function (xhr, status, error) {
                            showNotification("danger", 'Đã có lỗi xảy ra:', error);
                            reject(error); // Kết thúc promise với lỗi
                        });
                });

            }
        });

        $("#search-input").enterKey(function () {
            var button = $('#search-btn');
            if (!button.hasClass("loading"))
                $('#search-btn').click();
        });

        $('#datetime-local').datepicker({
            language: 'vi',

        })
        $('#ThemMoi').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    ChuyenHuong("external", "/LoaiSanPham/Edit/" + 0)
                    resolve();//cờ xác định kết thúc
                });
            }
        });
        // $('#NguoiChay').change(function () {
        //     $('#search-btn').click();
        // });

    });
</script>